version: "3"

services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: acgomes68/alpine-node-react:latest
    restart: always
    container_name: react-${APP_NAME}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GITHUB_URI=${API_GITHUB_URI}
      - REACT_APP_GITHUB_USERNAME=${API_GITHUB_USERNAME}
    command: yarn start
    stdin_open: true
    ports:
    - ${APP_PORT}:3000
    volumes:
    - ./:/usr/app
    - /usr/app/node_modules
